### ISSUE TITLE
Can not build Float 0.7.2

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/float#12]
The README refers to the `./configure` file but there is no one included in the archive.

**Comment by laurentbartholdi** [comment]
Version 0.7.3 should fix that problem -- I didn't know I had to include an
autogen.sh file.

On Wed, 11 May 2016 at 12:57 Alexander Konovalov <notifications@github.com>
wrote:

> The README refers to the ./configure file but there is no one included in
> the archive.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/gap-packages/float/issues/12>
>
-- 
Laurent Bartholdi
DMA, École Normale Supérieure, 45 rue d'Ulm, 75005 Paris. +33 14432 2060
Mathematisches Institut, Universität Göttingen, Bunsenstrasse 3-5, D-37073
Göttingen. +49 551 39 7826

**Comment by dimpase** [comment]
please see  comment https://github.com/gap-packages/float/commit/70958716ae402e034cb4b2db99fd56c44c729c68#diff-67e997bcfdac55191033d57a16d1408aR54 - there is broken autconf syntax there too...
