### ISSUE TITLE
Update external packages?

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/float#16]
Looking at your Makefile.am, it seems you optionally download stuff and build it. But the list is a bit outdated:
* fplll 4.0.1, but current are 4.0.4 and 5.03 
* mpfr 3.1.2 -> 3.1.5
* mpc 1.0.1 -> 1.0.3
* cxsc 2.5.3 -> 2.5.4

**Comment by laurentbartholdi** [comment]
Done, except for fplll.
