### ISSUE TITLE
Restriction to gap 4r8p9 or 4r9 ?

### ISSUE THREAD

**Issue by jgmbenoit** [gap-packages/float#35]
My understanding is that GAP 4r9 is not yet out (contrary to 4r8p9).

**Comment by alex-konovalov** [comment]
I may not fully understand our statement, but the development version of this package does not work with GAP 4.8 release series, and is intended for GAP 4.9 coming soon. It works with the master and stable-4.9 branches of the GAP repository.

**Comment by jgmbenoit** [comment]
Thanks for the clarification.
