### ISSUE TITLE
Can't load float in a Travis build of GAP stable-4.9 branch

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/float#36]
There is a problem with float built with `bin/BuildPackages.sh` in stable-4.9 branch. Build goes well, but its loading fails (see, for example, the end of the log file in https://travis-ci.org/gap-system/gap/jobs/336781671):
```
gap> #W dlopen() error: /home/travis/build/gap-system/gap/pkg/float-0.9.0/bin/x86_6\
4-pc-linux-gnu-default64/float.so: undefined symbol: atexit
Error, module '/home/travis/build/gap-system/gap/pkg/float-0.9.0/bin/x86_64-pc-linux-\
gnu-default64/float.so' not found in
  if not LOAD_DYN( arg[1], false ) then
    Error( "no support for dynamic loading" );
```
This has been observed while working on https://github.com/gap-system/gap/pull/2119 for Digraphs and float. The problem with Digraphs reported in https://github.com/gap-packages/Digraphs/issues/107

**Comment by alex-konovalov** [comment]
I can now observe the same problem in Travis CI builds for float which I am setting up in https://github.com/gap-packages/float/pull/37. Which is quite useful, because apparently it does not happen in [Travis builds for Digraphs](https://travis-ci.org/gap-packages/Digraphs). Hopefully we can compare setup for these two package and find out what's missing.

**Comment by laurentbartholdi** [comment]
This is 20 months old... is it still an issue?

**Comment by alex-konovalov** [comment]
Apparently now - it now builds fine in https://travis-ci.org/gap-packages/float 
as well as in package integration tests at https://travis-ci.org/gap-infra/gap-docker-pkg-tests-stable-4.11 and https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master
