### ISSUE TITLE
Migrating to gap-packages

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/float#9]
We have created new VO at https://github.com/gap-packages and suggest that all GAP packages could eventually migrate there - please consider doing so when it may be appropriate and less disruptive for your package.

**Comment by alex-konovalov** [comment]
The repository has been migrated, but all meta-information in the package still has to be updated to point to new URLs.

**Comment by fingolfin** [comment]
I guess this can be closed now?

**Comment by fingolfin** [comment]
No, this cannot be closed just yet, because the package has not been upload properly to <http://gap-packages.github.io/float> yet. In particular, it completly fails the validator test at http://www.gap-system.org/Packages/validator.html

Perhaps @laurentbartholdi could start using GitHubPages and ReleaseTools for this package, too?

**Comment by laurentbartholdi** [comment]
Yes, that's definitely on my todo list; it shouldn't be too difficult,
except the autoconfiguration of all sub-packages (cxsc, mpfr, mpc, mpfi) is
half-broken and I'll have to repair it.

On Sun, 28 Feb 2016 at 12:29 Max Horn <notifications@github.com> wrote:

> No, this cannot be closed just yet, because the package has not been
> upload properly to http://gap-packages.github.io/float yet. In
> particular, it completly fails the validator test at
> http://www.gap-system.org/Packages/validator.html
>
> Perhaps @laurentbartholdi <https://github.com/laurentbartholdi> could
> start using GitHubPages and ReleaseTools for this package, too?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gap-packages/float/issues/9#issuecomment-189848315>.
>
-- 
Laurent Bartholdi
DMA, École Normale Supérieure, 45 rue d'Ulm, 75005 Paris. +33 14432 2060
Mathematisches Institut, Universität Göttingen, Bunsenstrasse 3-5, D-37073
Göttingen. +49 551 39 7826

**Comment by alex-konovalov** [comment]
The package is now available at http://gap-packages.github.io/float/, so I am closing this issue. I've updated the URL of its PackageInfo.g at https://github.com/gap-system/gap-distribution/blob/master/DistributionUpdate/PackageUpdate/currentPackageInfoURLList
